runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /image
  static_dir: static/image
- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest